using System;
using System.Collections.Generic;
using System.Text;

namespace FH.Protobuf.SourceGenerator
{
    public enum PBSerializationTypeKind
    {
        Scalar,
        Enum,
        Message,
        Repeated,
        Map,
    }

    public sealed class PBSerializationContainingType
    {
        public string Accessibility = "public";
        public string Kind = "class";
        public string Name;
        public bool IsSealed;
    }

    public sealed class PBSerializationMessage
    {
        public string NamespaceName;
        public string Accessibility = "public";
        public string Name;
        public bool IsSealed;
        public bool ImplementIPBMessage = true;
        public bool GenerateSerialize = true;
        public bool GenerateUnserialize = true;
        public readonly List<PBSerializationContainingType> ContainingTypes = new List<PBSerializationContainingType>();
        public readonly List<PBSerializationField> Fields = new List<PBSerializationField>();
    }

    public sealed class PBSerializationField
    {
        public string Name;
        public int Number;
        public PBSerializationTypeRef Type;
    }

    public sealed class PBSerializationTypeRef
    {
        public PBSerializationTypeKind Kind;
        public string CSharpType;
        public string WriteMethod;
        public string ReadMethod;
        public PBSerializationTypeRef ElementType;
        public PBSerializationTypeRef KeyType;
        public PBSerializationTypeRef ValueType;

        public static PBSerializationTypeRef Scalar(string csharpType, string writeMethod, string readMethod)
        {
            return new PBSerializationTypeRef
            {
                Kind = PBSerializationTypeKind.Scalar,
                CSharpType = csharpType,
                WriteMethod = writeMethod,
                ReadMethod = readMethod,
            };
        }

        public static PBSerializationTypeRef Enum(string csharpType)
        {
            return new PBSerializationTypeRef
            {
                Kind = PBSerializationTypeKind.Enum,
                CSharpType = csharpType,
                WriteMethod = "WriteEnum",
                ReadMethod = "ReadEnum",
            };
        }

        public static PBSerializationTypeRef Message(string csharpType)
        {
            return new PBSerializationTypeRef
            {
                Kind = PBSerializationTypeKind.Message,
                CSharpType = csharpType,
                WriteMethod = "WriteMessage",
                ReadMethod = "ReadMessage",
            };
        }

        public static PBSerializationTypeRef Repeated(string csharpType, PBSerializationTypeRef elementType)
        {
            return new PBSerializationTypeRef
            {
                Kind = PBSerializationTypeKind.Repeated,
                CSharpType = csharpType,
                ElementType = elementType,
            };
        }

        public static PBSerializationTypeRef Map(string csharpType, PBSerializationTypeRef keyType, PBSerializationTypeRef valueType)
        {
            return new PBSerializationTypeRef
            {
                Kind = PBSerializationTypeKind.Map,
                CSharpType = csharpType,
                KeyType = keyType,
                ValueType = valueType,
            };
        }
    }

    public static class PBSerializationCodeGenTool
    {
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while",
        };

        public static string GenerateSource(PBSerializationMessage message)
        {
            CodeWriter writer = new CodeWriter();
            writer.Line("// <auto-generated />");
            writer.Line("#pragma warning disable 0649");
            writer.Line("#pragma warning disable 0169");
            writer.Line();
            writer.Line("using System;");
            writer.Line("using System.Collections.Generic;");
            writer.Line();

            if (!string.IsNullOrEmpty(message.NamespaceName))
            {
                writer.Line("namespace " + message.NamespaceName);
                writer.Line("{");
                writer.Indent++;
            }

            WritePartialDeclaration(writer, message);

            if (!string.IsNullOrEmpty(message.NamespaceName))
            {
                writer.Indent--;
                writer.Line("}");
            }

            return writer.ToString();
        }

        public static string GeneratePartialDeclaration(PBSerializationMessage message)
        {
            CodeWriter writer = new CodeWriter();
            WritePartialDeclaration(writer, message);
            return writer.ToString();
        }

        public static string GenerateMembers(PBSerializationMessage message)
        {
            CodeWriter writer = new CodeWriter();
            WriteMembers(writer, message);
            return writer.ToString();
        }

        private static void WritePartialDeclaration(CodeWriter writer, PBSerializationMessage message)
        {
            foreach (PBSerializationContainingType containingType in message.ContainingTypes)
            {
                writer.Line(GetTypeDeclarationPrefix(containingType.Accessibility, containingType.IsSealed) + containingType.Kind + " " + EscapeIdentifier(containingType.Name));
                writer.Line("{");
                writer.Indent++;
            }

            string interfaceText = message.ImplementIPBMessage ? " : global::FH.IPBMessage" : string.Empty;
            writer.Line(GetTypeDeclarationPrefix(message.Accessibility, message.IsSealed) + "class " + EscapeIdentifier(message.Name) + interfaceText);
            writer.Line("{");
            writer.Indent++;

            WriteMembers(writer, message);

            writer.Indent--;
            writer.Line("}");

            for (int i = message.ContainingTypes.Count - 1; i >= 0; i--)
            {
                writer.Indent--;
                writer.Line("}");
            }
        }

        private static void WriteMembers(CodeWriter writer, PBSerializationMessage message)
        {
            if (message.GenerateSerialize)
            {
                WriteSerialize(writer, message.Fields);
                writer.Line();
            }

            if (message.GenerateUnserialize)
            {
                WriteUnserialize(writer, message.Fields);
                writer.Line();
            }
        }

        private static string GetTypeDeclarationPrefix(string accessibility, bool isSealed)
        {
            if (string.IsNullOrEmpty(accessibility))
                accessibility = "public";
            return accessibility + (isSealed ? " sealed" : string.Empty) + " partial ";
        }

        private static void WriteSerialize(CodeWriter writer, List<PBSerializationField> fields)
        {
            writer.Line("public void Serialize(global::FH.PBWriter writer)");
            writer.Line("{");
            writer.Indent++;
            foreach (PBSerializationField field in fields)
                WriteSerializeField(writer, field);
            writer.Indent--;
            writer.Line("}");
        }

        private static void WriteSerializeField(CodeWriter writer, PBSerializationField field)
        {
            string member = "this." + EscapeIdentifier(field.Name);
            if (field.Type.Kind == PBSerializationTypeKind.Map)
            {
                writer.Line("if (" + member + " != null)");
                writer.Line("{");
                writer.Indent++;
                writer.Line("foreach (var item in " + member + ")");
                writer.Line("{");
                writer.Indent++;
                writer.Line("writer.BeginMessageField(" + field.Number + ");");
                WriteWriteValue(writer, field.Type.KeyType, 1, "item.Key");
                WriteWriteValue(writer, field.Type.ValueType, 2, "item.Value");
                writer.Line("writer.EndMessageField();");
                writer.Indent--;
                writer.Line("}");
                writer.Indent--;
                writer.Line("}");
                return;
            }

            if (field.Type.Kind == PBSerializationTypeKind.Repeated)
            {
                writer.Line("if (" + member + " != null)");
                writer.Line("{");
                writer.Indent++;
                writer.Line("foreach (var item in " + member + ")");
                writer.Line("{");
                writer.Indent++;
                WriteWriteValue(writer, field.Type.ElementType, field.Number, "item");
                writer.Indent--;
                writer.Line("}");
                writer.Indent--;
                writer.Line("}");
                return;
            }

            WriteWriteValue(writer, field.Type, field.Number, member);
        }

        private static void WriteWriteValue(CodeWriter writer, PBSerializationTypeRef type, int fieldNumber, string valueExpression)
        {
            if (type.Kind == PBSerializationTypeKind.Enum)
                writer.Line("writer.WriteEnum(" + fieldNumber + ", (int)" + valueExpression + ");");
            else if (type.Kind == PBSerializationTypeKind.Message)
                writer.Line("writer.WriteMessage(" + fieldNumber + ", " + valueExpression + ");");
            else
                writer.Line("writer." + type.WriteMethod + "(" + fieldNumber + ", " + valueExpression + ");");
        }

        private static void WriteUnserialize(CodeWriter writer, List<PBSerializationField> fields)
        {
            writer.Line("public bool Unserialize(global::FH.PBReader reader)");
            writer.Line("{");
            writer.Indent++;
            writer.Line("while (true)");
            writer.Line("{");
            writer.Indent++;
            writer.Line("if (reader.HasError())");
            writer.Indent++;
            writer.Line("return false;");
            writer.Indent--;
            writer.Line();
            writer.Line("var r = reader.ReadTag(out _, out int fieldIndex, out global::FH.EPBWireType wireType);");
            writer.Line("if (r == global::FH.PBReader.EReadTagResult.End)");
            writer.Indent++;
            writer.Line("return !reader.HasError();");
            writer.Indent--;
            writer.Line();
            writer.Line("if (r == global::FH.PBReader.EReadTagResult.Fail)");
            writer.Indent++;
            writer.Line("return false;");
            writer.Indent--;
            writer.Line();
            writer.Line("switch (fieldIndex)");
            writer.Line("{");
            writer.Indent++;
            foreach (PBSerializationField field in fields)
                WriteReadCase(writer, field);
            writer.Line("default: reader.SkipField(fieldIndex, wireType); break;");
            writer.Indent--;
            writer.Line("}");
            writer.Indent--;
            writer.Line("}");
            writer.Indent--;
            writer.Line("}");
        }

        private static void WriteReadCase(CodeWriter writer, PBSerializationField field)
        {
            string member = "this." + EscapeIdentifier(field.Name);
            writer.Line("case " + field.Number + ":");
            writer.Indent++;

            if (field.Type.Kind == PBSerializationTypeKind.Map)
            {
                writer.Line("if (reader.TryBeginMessageField(fieldIndex, wireType))");
                writer.Line("{");
                writer.Indent++;
                writer.Line(field.Type.KeyType.CSharpType + " key = " + GetDefaultValueExpression(field.Type.KeyType) + ";");
                writer.Line(field.Type.ValueType.CSharpType + " value = " + GetDefaultValueExpression(field.Type.ValueType) + ";");
                writer.Line("while (true)");
                writer.Line("{");
                writer.Indent++;
                writer.Line("if (reader.HasError())");
                writer.Indent++;
                writer.Line("break;");
                writer.Indent--;
                writer.Line();
                writer.Line("var entryR = reader.ReadTag(out _, out int entryFieldIndex, out global::FH.EPBWireType entryWireType);");
                writer.Line("if (entryR == global::FH.PBReader.EReadTagResult.End)");
                writer.Indent++;
                writer.Line("break;");
                writer.Indent--;
                writer.Line();
                writer.Line("if (entryR == global::FH.PBReader.EReadTagResult.Fail)");
                writer.Indent++;
                writer.Line("break;");
                writer.Indent--;
                writer.Line();
                writer.Line("switch (entryFieldIndex)");
                writer.Line("{");
                writer.Indent++;
                writer.Line("case 1:");
                writer.Indent++;
                WriteReadValueAssignment(writer, field.Type.KeyType, "key", "rawKey", "entryFieldIndex", "entryWireType");
                writer.Line("break;");
                writer.Indent--;
                writer.Line("case 2:");
                writer.Indent++;
                WriteReadValueAssignment(writer, field.Type.ValueType, "value", "rawValue", "entryFieldIndex", "entryWireType");
                writer.Line("break;");
                writer.Indent--;
                writer.Line("default: reader.SkipField(entryFieldIndex, entryWireType); break;");
                writer.Indent--;
                writer.Line("}");
                writer.Indent--;
                writer.Line("}");
                writer.Line("if (reader.EndMessageField(fieldIndex) && !reader.HasError())");
                writer.Line("{");
                writer.Indent++;
                writer.Line("if (" + member + " == null)");
                writer.Indent++;
                writer.Line(member + " = new " + field.Type.CSharpType + "();");
                writer.Indent--;
                writer.Line(member + "[key] = value;");
                writer.Indent--;
                writer.Line("}");
                writer.Indent--;
                writer.Line("}");
                writer.Line("break;");
                writer.Indent--;
                return;
            }

            if (field.Type.Kind == PBSerializationTypeKind.Repeated)
            {
                string tempName = "value" + field.Number;
                WriteReadValue(writer, field.Type.ElementType, tempName);
                writer.Line("if (!reader.HasError())");
                writer.Line("{");
                writer.Indent++;
                writer.Line("if (" + member + " == null)");
                writer.Indent++;
                writer.Line(member + " = new " + field.Type.CSharpType + "();");
                writer.Indent--;
                writer.Line(member + ".Add(" + tempName + ");");
                writer.Indent--;
                writer.Line("}");
                writer.Line("break;");
                writer.Indent--;
                return;
            }

            string singleTempName = "value" + field.Number;
            WriteReadValue(writer, field.Type, singleTempName);
            writer.Line("if (!reader.HasError())");
            writer.Indent++;
            writer.Line(member + " = " + singleTempName + ";");
            writer.Indent--;
            writer.Line("break;");
            writer.Indent--;
        }

        private static void WriteReadValue(CodeWriter writer, PBSerializationTypeRef type, string tempName)
        {
            if (type.Kind == PBSerializationTypeKind.Enum)
            {
                writer.Line("reader.ReadEnum(fieldIndex, wireType, out int raw" + tempName + ");");
                writer.Line(type.CSharpType + " " + tempName + " = (" + type.CSharpType + ")raw" + tempName + ";");
            }
            else if (type.Kind == PBSerializationTypeKind.Message)
            {
                writer.Line("reader.ReadMessage<" + type.CSharpType + ">(fieldIndex, wireType, out var " + tempName + ");");
            }
            else
            {
                writer.Line("reader." + type.ReadMethod + "(fieldIndex, wireType, out var " + tempName + ");");
            }
        }

        private static void WriteReadValueAssignment(CodeWriter writer, PBSerializationTypeRef type, string targetExpression, string rawName, string fieldIndexExpression, string wireTypeExpression)
        {
            if (type.Kind == PBSerializationTypeKind.Enum)
            {
                writer.Line("reader.ReadEnum(" + fieldIndexExpression + ", " + wireTypeExpression + ", out int " + rawName + ");");
                writer.Line(targetExpression + " = (" + type.CSharpType + ")" + rawName + ";");
            }
            else if (type.Kind == PBSerializationTypeKind.Message)
            {
                writer.Line("reader.ReadMessage<" + type.CSharpType + ">(" + fieldIndexExpression + ", " + wireTypeExpression + ", out " + targetExpression + ");");
            }
            else
            {
                writer.Line("reader." + type.ReadMethod + "(" + fieldIndexExpression + ", " + wireTypeExpression + ", out " + targetExpression + ");");
            }
        }

        private static string GetDefaultValueExpression(PBSerializationTypeRef type)
        {
            if (type.Kind == PBSerializationTypeKind.Scalar)
            {
                if (type.ReadMethod == "ReadString")
                    return "string.Empty";
                if (type.ReadMethod == "ReadBytes")
                    return "global::System.Array.Empty<byte>()";
            }

            return "default(" + type.CSharpType + ")";
        }

        private static string EscapeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_";
            return CSharpKeywords.Contains(name) ? "@" + name : name;
        }

        private sealed class CodeWriter
        {
            private readonly StringBuilder _sb = new StringBuilder();
            public int Indent;

            public void Line()
            {
                _sb.AppendLine();
            }

            public void Line(string value)
            {
                for (int i = 0; i < Indent; i++)
                    _sb.Append("    ");
                _sb.AppendLine(value);
            }

            public override string ToString()
            {
                return _sb.ToString();
            }
        }
    }
}
