using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using NativeLibTool.Utilities;

namespace NativeLibTool.Services
{
    internal static class LocalMavenTempGradleWriter
    {
        public static string Write(string localMavenDirectory)
        {
            FileCopyUtility.EnsureDirectory(localMavenDirectory);

            var packages = FindPackages(localMavenDirectory).ToList();
            var groups = packages
                .Select(package => package.GroupId)
                .Where(group => !string.IsNullOrWhiteSpace(group))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(group => group, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var builder = new StringBuilder();
            builder.AppendLine("// Generated by NativeLibTool.");
            builder.AppendLine("// Copy the maven block into Assets/Plugins/Android/settingsTemplate.gradle");
            builder.AppendLine("// inside dependencyResolutionManagement { repositories { ... } }.");
            builder.AppendLine("// Copy the dependency lines into the proper module dependencies block.");
            builder.AppendLine("// Replace implementation with a flavor-specific configuration if the project needs it.");
            builder.AppendLine();
            builder.AppendLine("def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace(\"\\\\\", \"/\")");
            builder.AppendLine();
            builder.AppendLine("maven {");
            builder.AppendLine("    url (unityProjectPath + \"/LocalMaven\")");
            if (groups.Count > 0)
            {
                builder.AppendLine("    content {");
                foreach (var group in groups)
                {
                    builder.AppendLine("        includeGroup \"" + EscapeGradleString(group) + "\"");
                }

                builder.AppendLine("    }");
            }

            builder.AppendLine("}");
            builder.AppendLine();
            builder.AppendLine("// Example:");
            builder.AppendLine("// dependencies {");
            foreach (var package in packages)
            {
                builder.AppendLine("//     implementation \"" + EscapeGradleString(package.Coordinate) + "\"");
            }

            builder.AppendLine("// }");
            builder.AppendLine();
            builder.AppendLine("// Coordinates:");
            foreach (var package in packages)
            {
                builder.AppendLine("// " + EscapeGradleString(package.Coordinate));
            }

            var outputPath = Path.Combine(localMavenDirectory, "temp.gradle");
            File.WriteAllText(outputPath, builder.ToString(), new UTF8Encoding(false));
            return outputPath;
        }

        private static IEnumerable<MavenPackage> FindPackages(string localMavenDirectory)
        {
            if (!Directory.Exists(localMavenDirectory))
            {
                return Enumerable.Empty<MavenPackage>();
            }

            return Directory.GetFiles(localMavenDirectory, "*.pom", SearchOption.AllDirectories)
                .Select(TryReadPackage)
                .Where(package => package != null)
                .GroupBy(package => package.Coordinate, StringComparer.OrdinalIgnoreCase)
                .Select(group => group.First())
                .OrderBy(package => package.GroupId, StringComparer.OrdinalIgnoreCase)
                .ThenBy(package => package.ArtifactId, StringComparer.OrdinalIgnoreCase)
                .ThenBy(package => package.Version, StringComparer.OrdinalIgnoreCase);
        }

        private static MavenPackage TryReadPackage(string pomPath)
        {
            try
            {
                var document = XDocument.Load(pomPath);
                var root = document.Root;
                if (root == null)
                {
                    return null;
                }

                var ns = root.Name.Namespace;
                var groupId = Value(root, ns, "groupId");
                var artifactId = Value(root, ns, "artifactId");
                var version = Value(root, ns, "version");

                if (string.IsNullOrWhiteSpace(groupId) ||
                    string.IsNullOrWhiteSpace(artifactId) ||
                    string.IsNullOrWhiteSpace(version))
                {
                    return null;
                }

                return new MavenPackage
                {
                    GroupId = groupId.Trim(),
                    ArtifactId = artifactId.Trim(),
                    Version = version.Trim()
                };
            }
            catch
            {
                return null;
            }
        }

        private static string Value(XElement root, XNamespace ns, string name)
        {
            var direct = root.Element(ns + name);
            if (direct != null)
            {
                return direct.Value;
            }

            var parent = root.Element(ns + "parent");
            return parent == null ? string.Empty : (parent.Element(ns + name) == null ? string.Empty : parent.Element(ns + name).Value);
        }

        private static string EscapeGradleString(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private sealed class MavenPackage
        {
            public string GroupId { get; set; }
            public string ArtifactId { get; set; }
            public string Version { get; set; }

            public string Coordinate
            {
                get { return GroupId + ":" + ArtifactId + ":" + Version; }
            }
        }
    }
}
